# Generated by Django 3.0.6 on 2020-05-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
